### ISSUE TITLE
Require LICENSE file

### ISSUE THREAD

**Issue by 61131** [burtyb/clusterhat-image#1]
I am in the process of putting together a series of Yocto recipe for building minimal development images for Raspberry Pi hardware installed within a ClusterHAT configuration. As part of the quality assurance checks implemented within this build pipeline, I need to confirm the licensing of the clusterhat-image components.  

Please add a LICENSE file with preferred open-source license for content within the clusterhat-image repository.  Alternatively, I can add this file through a pull request if you would like to nominate your preferred licensing for these files.

**Comment by burtyb** [comment]
A licence file has been added in #2
