### ISSUE TITLE
90-clusterctrl.rules:18 Invalid value

### ISSUE THREAD

**Issue by Vitexus** [burtyb/clusterhat-image#12]
```
May 14 10:24:36 cbridge systemd-udevd[331]: /etc/udev/rules.d/90-clusterctrl.rules:18 Invalid value "/bin/bash -c 'echo 0x3171 0x$ID_MODEL_ID >> /sys/bus/usb/drivers/i2c-tiny-usb/new_id'" for RUN (char 29: invalid substitution type), ignoring.
```

**Comment by cobber** [comment]
almost the same here:

```
# journalctl -b | grep -i cluster
Aug 04 17:59:18 cl0 systemd-udevd[174]: /etc/udev/rules.d/90-clusterctrl.rules:18 Invalid value "/bin/bash -c 'echo 0x3171 0x$ID_MODEL_ID >> /sys/bus/usb/drivers/i2c-tiny-usb/new_id'" for RUN (char 29: invalid substitution type), ignoring, but please fix it.
Aug 04 17:59:20 cl0 systemd-fsck[242]: /dev/mmcblk0p1: 476 files, 26413/130554 clusters
Aug 04 17:59:21 cl0 systemd[1]: Starting ClusterCTRL init...
Aug 04 17:59:25 cl0 systemd[1]: Finished ClusterCTRL init.
Aug 04 17:59:25 cl0 systemd[1]: Started ClusterCTRL rpiboot for SD cardless booting.
Aug 04 17:59:25 cl0 rpiboot[432]: Boot directory '/var/lib/clusterctrl/boot/'
Aug 04 17:59:25 cl0 rpiboot[432]: Loading: /var/lib/clusterctrl/boot//bootcode.bin
```

clusterctrl.rules:18 Invalid value "/bin/bash -c 'echo 0x3171 0x$ID_MODEL_ID ...
for RUN (char 29: invalid substitution type), ignoring, _**but please fix it**_.
char 29 is the `$` of `$ID_MODEL_ID`.

I have no idea how to "fix it" :-(

I also have no idea if this actually causes any problems or not.
(it is not clear to me if "ignoring" means the invalid character was ignored or the entire rule was not run)

The things you find when you look through your system logs ;-)

System Info:
- my `/etc/udev/rules.d/90-clusterhat.rules` file is identical to [90-clusterhat.rules](https://github.com/burtyb/clusterhat-image/blob/master/files/etc/udev/rules.d/90-clusterctrl.rules) (version as of 2024-08-04)

```
# raspinfo | head -n 8
System Information
------------------

Raspberry Pi 3 Model B Plus Rev 1.3
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
```
```
# uname -a
Linux cl0 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```

**Comment by burtyb** [comment]
In your case @cobber it won't cause any issues as status says "clusterctrl:False" (the rule is used on ClusterCTRL boards controlled by I2C over USB).

**Comment by cobber** [comment]
... and the error is gone 👍 
👏 
Thanks! (on behalf of those who it may have effected ;-)
