### ISSUE TITLE
/sbin/clusterctrl not working with Python 3 

### ISSUE THREAD

**Issue by psergiu** [burtyb/clusterhat-image#5]
Hi,
I switched the default Python on the cluster-hat image to Python 3.7 and /sbin/clusterctrl has the following error:

```
# python --version
Python 3.7.3

# clusterctrl
  File "/sbin/clusterctrl", line 836
    sys.exit(1)
              ^
TabError: inconsistent use of tabs and spaces in indentation
```
After replacing tabs with spaces in line 836 of /sbin/clusterctrl :
```
# clusterctrl
Traceback (most recent call last):
  File "/sbin/clusterctrl", line 330, in <module>
    import xra1200
  File "/usr/share/clusterctrl/python/xra1200.py", line 39
    except IOError, err:
                  ^
SyntaxError: invalid syntax
```
after updating to "except IOError as err:" in /usr/share/clusterctrl/python/xra1200.py line 39 "clusterctrl on" works but there's still more work to be done:
```
# clusterctrl status
clusterhat:{}
Traceback (most recent call last):
  File "/sbin/clusterctrl", line 613, in <module>
    print ( "clusterhat:{}" ).format( clusterhat )
AttributeError: 'NoneType' object has no attribute 'format'
```

_2to3_ also produces a sizable diff 

Thank you.

**Comment by burtyb** [comment]
It's unlikely I'll update the current script as I'm working on a (Python 3) replacement with more features. If you still have python2 available I'd advise changing the shebang to explicitly use that for the moment.

**Comment by burtyb** [comment]
I've just pushed a couple of changes which should allow the "clusterctrl" script to work with Python 2 or 3.

If you still need Python 3 support and give it a try please let me know how you get on.
