### ISSUE TITLE
DHCP fallback on p{1..4} on CBRIDGE images when controller reboots

### ISSUE THREAD

**Issue by ScrumpyJack** [burtyb/clusterhat-image#7]
Just upgraded to the new buster image. Thank you for providing that. It makes life much easier.

Small problem with resetting the controller though. Here's what gives:
Boot the controller and it gets DHCP from upstream (local home router). Lovely.
Boot p{1..4} and they also get an DHCP from upsteam. Also lovely.
But if you reboot the controller, the p{1..4} USB gadget net interfaces reset and fall back to clusterctrl_fallback_usb0. 

Is that the expected behaviour? I don't remember that being the behaviour in the Stretch images.

**Comment by burtyb** [comment]
Please use https://groups.google.com/forum/#!forum/clusterhat for support on using the images.
