### ISSUE TITLE
This is for the Pi4 base unit, or the PiZero board that slot into the cluster hat?

### ISSUE THREAD

**Issue by paul-hammant** [burtyb/clusterhat-image#8]

**Comment by burtyb** [comment]
CBRIDGE is the base image which it always creates. 

The USBBOOT Px images are then made from the CBRIDGE image (if USBBOOTLITE/USBBOOTSTD/USBBOOTFULL have been set to something other than 0 in config-local.sh).

CNAT/P1/px are again made from the CBRIDGE image by updating the "init=.." part in /boot/cmdline.txt to reconfigure on first boot.

**Comment by paul-hammant** [comment]
I'm sorry, I didn't quite understand that. Maybe I'm not the right audience for this software.
